### PR TITLE
Amethyst CLI rewrite

### PR DESCRIPTION
**Pull request by torkleyy**

### CODE REVIEW

**Review by Rhuagh — APPROVED** [review]

**Review by Xaeroxe — APPROVED** [review]
Looks great, but I'm not sure I understand what the build script is doing.

**Comment by torkleyy** [comment]
@Xaeroxe So basically there is a `template` folder. It contains an `index.ron` file. This file lists all the files we actually want in the final template. And the build script just includes these listed files into the source code (`_template_files.rs` which is included by `src/new.rs`).

**Comment by Xaeroxe** [comment]
Oh huh, that's an interesting way of doing that.  Definitely saves a lot of work though :D Can you add that explanation as a comment at the top of the build script?  Then I think we'll be ready to merge.

**Comment by Xaeroxe** [comment]
Tested locally, works great,  thanks a ton @torkleyy 

bors r+

**Comment by Xaeroxe** [comment]
Uh that's awkward.  Ok well here goes.

**Pull request merged**
