### PR TITLE
Check for most commands if the project is an amethyst project

### PR DESCRIPTION
**Pull request by White-Oak**
A function to check if a specified project appears to be a valid amethyst project.
- [x] Decide if `is_amethyst_project` should return bool or `CmdResult`. The latter is more convinient.
- [x] Current implementation checks only existence of config.yml and yml parsability. Probably it should also check contents, but they are not specified by the current documentation.
- [x] Tests
  - [x] Fail for build command if not an amethyst project

### CODE REVIEW

**Comment by White-Oak** [comment]
pinging @ebkalderon for a review

**Comment by ebkalderon** [comment]
@White-Oak Thanks! Let me finish reviewing #23 first and I'll look at this one.

**Comment by LucioFranco** [comment]
@White-Oak Should you not check if there is like a project name or something inside the yaml file?

**Comment by White-Oak** [comment]
@LucioFranco the template of a new project's config is 

``` yml
---
logging:
    file_path: "new_project.log"
    output_verbosity: medium
    logging_verbosity: debug 

display:
    brightness: 1.0
    fullscreen: false
    resolution: [1024, 768]
```

We will probably need some docs on that file to see what should be in it.

**Comment by LucioFranco** [comment]
@White-Oak Okay maybe we can create an issue to discuss that. Besides that, I think everything here looks good!

**Comment by White-Oak** [comment]
@LucioFranco would you create one?

**Comment by LucioFranco** [comment]
@White-Oak yeah i can do that or should I wait for us to move to the new repo?

**Comment by ebkalderon** [comment]
@LucioFranco From what I can understand, the rollover is seamless. Still, you can create it now and then I'll migrate, just in case.

**Comment by White-Oak** [comment]
Merged master and resolved conflicts. Also added check for deploy subcommand.

**Comment by ebkalderon** [comment]
This looks good, guys! Let's merge.

**Pull request merged**
