### PR TITLE
Shards subcommands

### PR DESCRIPTION
**Pull request by White-Oak**
Implemented `add <name>` and `remove <name>`.

Currently, they add and remove 'features' from `Cargo.toml` of a project.

No tests, cause not sure how to test this. Maybe try to build a project?

This is an implementation of CLI task in [Shards RFC](https://github.com/amethyst/amethyst/issues/34).

### CODE REVIEW

**Comment by ebkalderon** [comment]
@White-Oak Hmm, it is too early to properly test this feature since we don't have a concrete implementation of the engine modules concept. Nor do we have any Cargo features in the engine to actually try, and we don't have a spec for zipped modules.

**Comment by White-Oak** [comment]
@ebkalderon It's a part one of "modules/shards" project, featuring "features".

**Comment by ebkalderon** [comment]
@White-Oak We should probably make an RFC for this, given the discussion we were all having on the `general` room. Implementing this properly might be an involved process.

**Comment by White-Oak** [comment]
@ebkalderon Certainly. But this is "the part one" as I mentioned erlier, so apart from naming it and naming commands it wouldn't have much alternatives (:

**Comment by White-Oak** [comment]
@ebkalderon if we agreed on CLI task in RFC for shards, this is ready to be merged.

**Comment by ebkalderon** [comment]
@White-Oak It looks like there are some conflicts with this pull request? Could you please resolve them? I think this is ready to be merged. We can keep discussing specifics on the shards RFC (amethyst/amethyst#34) and iterate on this as needed.

**Comment by White-Oak** [comment]
@ebkalderon sure! I'll do it asap

**Comment by White-Oak** [comment]
@ebkalderon Renamed modules to shards and used `amethyst add <name>` as a syntax.

**Comment by ebkalderon** [comment]
Sorry for the delayed response. I think this pull request is essentially done, despite our inability to effectively test it. I'll merge this now!

**Pull request merged**
