### PR TITLE
CI and code coverage

### PR DESCRIPTION
**Pull request by BradLugo**
This adds a few improvements to the CI:
- Format checking
- Linting
- Code coverage sending via kcov to codecov
- Test on all major operating systems

Also adds code coverage badge to README

### CODE REVIEW

**Comment by BradLugo** [comment]
First time working with Travis CI. Any feedback or suggestions are appreciated

**Comment by BradLugo** [comment]
Thought about using [tarpaulin](https://github.com/xd009642/tarpaulin) instead of [kcov](https://github.com/SimonKagstrom/kcov). Like to get some opinions on that. The obvious advantage is not having all the `make` and `cmake` nonsense in the build script.

**Comment by torkleyy** [comment]
> Thought about using tarpaulin instead of kcov. Like to get some opinions on that. The obvious advantage is not having all the make and cmake nonsense in the build script.

I tried that about a month ago, but it's not mature enough.

**Review by torkleyy — APPROVED** [review]
Looks great!

**Pull request merged**
