### PR TITLE
Added a convenient error message when running cargo test on Windows

### PR DESCRIPTION
**Pull request by White-Oak**

### CODE REVIEW

**Comment by ebkalderon** [comment]
@White-Oak I'm pretty sure we shouldn't say "Linux" specifically, since it should be okay on other Unix-like systems such as BSD. Do you know if `unix` also counts Mac OS X? If so, that can be counted as well.

I'd recommend changing the message to say "Unix-like systems" instead of "Linux".

Maybe we should consider moving the tests over to native Rust at some point so they can work on all platforms.

**Comment by White-Oak** [comment]
@eblalderon it would be cool to have a `POSIX` target :)

**Comment by White-Oak** [comment]
@ebkalderon I've changed `unix` to `not windows`. Eventually, tests would need to be rewritten in Rust, but that's a big and tirsome task, so until then this is a small change to help Windows users understand that it's not a code, but tests' nature, that fails them.

**Comment by ebkalderon** [comment]
@White-Oak I agree, this is good enough for now. Thank you! Let's merge this.

**Pull request merged**
