### PR TITLE
Added support for running cli tests via cargo

### PR DESCRIPTION
**Pull request by LucioFranco**
Small PR to allow any user to clone the repo and run `cargo test` to run the tests. I didn't include this in my last PR because I did not know if you wanted this or not.

### CODE REVIEW

**Comment by ebkalderon** [comment]
@LucioFranco Unfortunately, compiling and running `cargo test` in the top-level repo directory results in the following error:

```
     Running target/debug/amethyst-5112309b44bf399c

running 1 test
test cli ... FAILED

failures:

---- cli stdout ----
	thread 'cli' panicked at 'assertion failed: output.status.success()', src/cli/main.rs:90
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    cli

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Here is the backtrace:

```
stack backtrace:
   1:     0x55fa4f6d6f70 - sys::backtrace::tracing::imp::write::h752705b18648d1caEIv
   2:     0x55fa4f6dbaff - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.45061
   3:     0x55fa4f6db6c3 - panicking::default_handler::hd7da873c55525eaaRxA
   4:     0x55fa4f6cc05c - sys_common::unwind::begin_unwind_inner::h9832d329b70049c9Xwu
   5:     0x55fa4f68fd97 - sys_common::unwind::begin_unwind::h9276032947351430688
                        at ../src/libstd/sys/common/unwind/mod.rs:219
   6:     0x55fa4f6900c2 - cli::h9f1580ed80c5ee359oa
                        at /home/ekalderon/amethyst_tools-cargo-test/<std macros>:3
   7:     0x55fa4f6af2d6 - boxed::F.FnBox<A>::call_box::h13776863799292905253
   8:     0x55fa4f6b19cb - sys_common::unwind::try::try_fn::h5918694580207012494
   9:     0x55fa4f6d61fb - __rust_try
  10:     0x55fa4f6d618d - sys_common::unwind::inner_try::hfb91b5cfe185b795Ztu
  11:     0x55fa4f6b1d4a - boxed::F.FnBox<A>::call_box::h11273819929398351734
  12:     0x55fa4f6da0c9 - sys::thread::Thread::new::thread_start::h33a79b9c7e674b88Huz
  13:     0x7f068e25a423 - start_thread
  14:     0x7f068dd83cbc - clone
  15:                0x0 - <unknown>
```

**Comment by ebkalderon** [comment]
@LucioFranco Unfortunately, for me compiling the code and running `cargo test` while in the same directory as the `tests.sh` script gave me the following failure:

```
     Running target/debug/amethyst-5112309b44bf399c

running 1 test
test cli ... FAILED

failures:

---- cli stdout ----
    thread 'cli' panicked at 'assertion failed: output.status.success()', src/cli/main.rs:90
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    cli

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Do you have any ideas how to fix this?

**Comment by LucioFranco** [comment]
@ebkalderon That actually means the test exited with a non-zero status because it failed on asserting if the test had passed or not. That means that the test code actually behaves like it should. So now the question is what went wrong in the tests.sh script.

**Comment by LucioFranco** [comment]
@ebkalderon I added some test cleanup that may have been causing you issues. It works on my mac and seems like the program ran. I also added some logging so when it does panic you can see why.

**Comment by ebkalderon** [comment]
@LucioFranco This pull request works for me, thanks! Merging.

**Pull request merged**
