### PR TITLE
New project template from submodule

### PR DESCRIPTION
**Pull request by lschmierer**
- [ ] Choose license for `project_template` https://github.com/amethyst/project_template/issues/1

### CODE REVIEW

**Comment by White-Oak** [comment]
Did you notice, that you run `cargo fmt` and commited all of it in PR?

**Comment by lschmierer** [comment]
Yes, just noticed. Is that bad?
I thought we use rustfmt anyway.

**Comment by lschmierer** [comment]
Well, ok there definetly need something to be fixed in `deploy.rs`.

**Comment by ebkalderon** [comment]
@lschmierer These code additions look great! Thanks, everything looks a lot cleaner. :+1:

I was thinking, though, could we technically keep the project template, still unzipped, inside the `amethyst_tools` repository instead of in a separate repo?

**Comment by lschmierer** [comment]
Yeah sure, it's just a matter of taste, I guess.

**Comment by ebkalderon** [comment]
It's your choice too, man. We can keep it as a submodule. :smile: I think I'll merge this.

**Pull request merged**
