### PR TITLE
Expand the templating system

### PR DESCRIPTION
**Pull request by Moxinilian**
This PR expands the templating system by introducing a rich wrapper around the [Liquid Templating Language](https://shopify.github.io/liquid/).

The templates/ directory storing the templates in the root of the crates is structured as follow: each folder in its root represents an amethyst version, containing the templates this version and onward will use.
For example, if we have the folders "0.6.0" and "0.7.1", templates for versions 0.6.5 or 0.7.0 will be searched in the folder "0.6.0", and templates for versions 0.7.1 or 0.8.0 will be searched in the folder "0.7.1", following semver ordering.

Those version folders contain subfolders containing the different template they describe. As of now, the only template is "main" designating the template for a new amethyst project, but in the future it will also include templates such as a minimal iOS app bundle. Note that a version folder does not have to contain a copy of all template types, as if one has not changed, it can be retrieved from previous versions. Templates need to be added only when they are actually changed. If it is deemed appropriate, this behavior can be used to set a high default version without updating the templates by creating an empty folder for this version.

In order to support contextual data in template files, this PR uses the crate ``liquid`` to handle templating. Files with extension GDPU (God Damn Pink Unicorn, specifications courtesy of @Rhuagh) will be processed as a liquid template, allowing dynamic content in template files. The extension is then removed in the output. Note that the parameter ``amethyst_version`` will automatically be included to liquid parameters, containing the actually requested version. Please also note that for a text file to have its line endings be correctly chosen depending on the OS, it needs to have the GDPU extension, but it does not have to actually take advantage of parsing.

In order to deploy a template, this PR provides the function ``deploy``, taking as parameters a template name, an optional version (if none provided, it will take the latest available), a path to the output folder, liquid parameters (type exported by template.rs for convenience) and a renaming HashMap.

The renaming HashMap acts as a dictionary between filenames in the template and filenames in the output. For example, if it contains the entry ``("__Cargo__.toml", "Cargo.toml")``, all files named ``__Cargo__.toml`` in the template will be renamed ``Cargo.toml`` in the output. This is useful when names perturbate the integrity of the repository, or when they depend on contextual data. Note that the translation is done before the search for GDPU extensions.

Templates support all file types and directory structures. symlinks may be supported while not tested. Example usage of all of this can be found in ``new.rs``.

### CODE REVIEW

**Review by torkleyy — APPROVED** [review]
Looks good to me, thanks!

**Review by Rhuagh — APPROVED** [review]

**Comment by AnneKitsune** [comment]
Is this ready for review or still requires work?

**Comment by Moxinilian** [comment]
It's been ready for a week now ahah

**Review by Xaeroxe — APPROVED** [review]
LGTM!  Thanks!

**Pull request merged**
