### PR TITLE
Add git init

### LINKED ISSUE #73: amethyst cli doesn't init git repo
See #10, there is also no .gitignore created (but these go hand in hand)

As the amethyst CLI tries to emulate cargo cli, in my opinion it should also initialize a git repo like cargo does.

### Amethyst CLI (sorry for the time it took me to derp around)

peek 2019-01-15 17-19

### Cargo CLI

peek 2019-01-15 17-22

### PR DESCRIPTION
**Pull request by Xaeroxe**
Fixes #73

### CODE REVIEW

**Comment by Xaeroxe** [comment]
cc @WillowBlade

**Review by azriel91 — APPROVED** [review]
Cool

**Comment by Willowblade** [comment]
Sweet, thanks! :D will contribute to Amethyst docs this weekend!

**Pull request merged**
