### PR TITLE
Code Generation!

### PR DESCRIPTION
**Pull request by AnneKitsune**
Finally, a easy way to create my components/states/systems when I'm programming using nano :D

Usage:
amethyst gen-list
amethyst gen template-name type-name [-o output-file]

The template-name can be shortened.
For example, we have the following templates:
-component
-state
-system

If you write "c" as your template-name, it matches to component.
If you write "s" as your template-name, it matches to state (first one that starts_with(arg))

### CODE REVIEW

**Comment by AnneKitsune** [comment]
Fix for the tests on its way. Compiling is a bit slow since I updated rust and its recompiling everything.

**Review by Moxinilian — COMMENTED** [review]
Why didn't you use the existing templating system?

**Comment by AnneKitsune** [comment]
The current templating system is too specific. It checks for versions and does other things. I also like it more when the code is separated with more fn.

**Comment by Moxinilian** [comment]
You will need versioning here too however.

**Comment by Moxinilian** [comment]
Besides, you don't need to care about versioning in the current system, it's optional.
It just makes it future-proof and avoid to have duplicate code all over the place.

**Comment by torkleyy** [comment]
@jojolepro Are you still working on this?

**Comment by AnneKitsune** [comment]
I'm not working on it, but this seems to still contain useful stuff.

**Comment by torkleyy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
