### PR TITLE
Upgrade packages and use Rust 2018

### LINKED ISSUE #82: Upgrade packages and fix CI build
As discussed in #81, we should upgrade `amethyst/tools` to use Rust 2018 and look into any packages that are breaking and could break the CI build.

### PR DESCRIPTION
**Pull request by BradLugo**
Closes #82

### CODE REVIEW

**Comment by BradLugo** [comment]
These changes don't look right to me. I'd appreciate an additional set of eyes on this and any pointers on how to improve this.

**Review by torkleyy — APPROVED** [review]
Looks good to me!

**Comment by torkleyy** [comment]
Anything blocking this?

**Comment by torkleyy** [comment]
Makes Travis happy, so I guess I can just merge. Thanks!
bors r+

**Pull request merged**
